version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - ${PORTAINER_JELLYFIN_PORT}:8096
    volumes:
      - ./config:/config
      - /home/adrianf/Movies & Series/TV Shows/:/data/TV Shows
      - /home/adrianf/Movies & Series/Movies/:/data/Movies
