version: "3.9"

services:
  postgresql_core:
    image: postgres:18-bookworm
    container_name: postgresql_core
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PORTAINER_CORE_DB_PASSWORD}
      - POSTGRES_DB=${PORTAINER_CORE_DB_DATABASE}
      - POSTGRES_USER=${PORTAINER_CORE_DB_USERNAME}
    ports:
      - ${PORTAINER_CORE_DB_PORT}:5432
    volumes:
      - postgresql_core:/var/lib/postgresql
  postgresql_operations:
    image: postgres:18-bookworm
    container_name: postgresql_operations
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PORTAINER_OPERATIONS_DB_PASSWORD}
      - POSTGRES_DB=${PORTAINER_OPERATIONS_DB_DATABASE}
      - POSTGRES_USER=${PORTAINER_OPERATIONS_DB_USERNAME}
    ports:
      - ${PORTAINER_OPERATIONS_DB_PORT}:5433
    volumes:
      - postgresql_operations:/var/lib/postgresql
  nodejs:
    build: .
    container_name: nodejs
    restart: unless-stopped
    ports:
      - ${PORTAINER_NODEJS_PORT}:${PORTAINER_NODEJS_PORT}
    depends_on:
      - postgresql_core
      - postgresql_operations
    volumes:
      - ./app:/app

volumes:
  postgresql_core:
  postgresql_operations: